spring.application.name=NEEDU-BE
spring.profiles.default=local

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

needu.rate-limit.policies.personal-recommendations.method=GET
needu.rate-limit.policies.personal-recommendations.path-pattern=/api/v1/users/me/personal-recommendations
needu.rate-limit.policies.personal-recommendations.limit=120
needu.rate-limit.policies.personal-recommendations.window=1m
needu.rate-limit.policies.personal-recommendations.maximum-size=100000
